"""振盪器策略模塊"""

from .oscillator_strategies import OSCILLATOR_STRATEGIES
from .advanced_oscillators import ADVANCED_OSCILLATOR_STRATEGIES
from .complete_oscillators import COMPLETE_OSCILLATOR_STRATEGIES

# 合併所有振盪器策略（16 個）
ALL_OSCILLATOR_STRATEGIES = {**OSCILLATOR_STRATEGIES, **ADVANCED_OSCILLATOR_STRATEGIES, **COMPLETE_OSCILLATOR_STRATEGIES}

__all__ = ['ALL_OSCILLATOR_STRATEGIES', 'OSCILLATOR_STRATEGIES', 'ADVANCED_OSCILLATOR_STRATEGIES', 'COMPLETE_OSCILLATOR_STRATEGIES']
