"""振盪器策略模塊"""

from .oscillator_strategies import OSCILLATOR_STRATEGIES
from .advanced_oscillators import ADVANCED_OSCILLATOR_STRATEGIES

# 合併所有振盪器策略
ALL_OSCILLATOR_STRATEGIES = {**OSCILLATOR_STRATEGIES, **ADVANCED_OSCILLATOR_STRATEGIES}

__all__ = ['ALL_OSCILLATOR_STRATEGIES', 'OSCILLATOR_STRATEGIES', 'ADVANCED_OSCILLATOR_STRATEGIES']
