"""執行算法模塊 - 13/13 完成（100%）"""

from .execution_strategies import EXECUTION_STRATEGIES
from .execution_complete import EXECUTION_COMPLETE_STRATEGIES
from .execution_final import EXECUTION_FINAL_STRATEGIES

# 合併所有執行策略（13 個）
ALL_EXECUTION_STRATEGIES = {**EXECUTION_STRATEGIES, **EXECUTION_COMPLETE_STRATEGIES, **EXECUTION_FINAL_STRATEGIES}

__all__ = [
    "ALL_EXECUTION_STRATEGIES",
    "EXECUTION_STRATEGIES",
    "EXECUTION_COMPLETE_STRATEGIES",
    "EXECUTION_FINAL_STRATEGIES",
]
