"""AI/ML 策略模塊 - 16/16 完成（100%）"""

from .ai_strategies import AI_ML_STRATEGIES
from .ai_complete import AI_ML_COMPLETE_STRATEGIES
from .ai_final import AI_ML_FINAL_STRATEGIES

# 合併所有 AI/ML 策略（16 個）
ALL_AI_ML_STRATEGIES = {**AI_ML_STRATEGIES, **AI_ML_COMPLETE_STRATEGIES, **AI_ML_FINAL_STRATEGIES}

__all__ = ["ALL_AI_ML_STRATEGIES", "AI_ML_STRATEGIES", "AI_ML_COMPLETE_STRATEGIES", "AI_ML_FINAL_STRATEGIES"]
