"""趋势策略模塊 - 18/18 完成（100%）"""

from .hull_ma_strategy import ADVANCED_TREND_STRATEGIES as HULL_TEMA
from .advanced_trend_strategies import ADVANCED_TREND_STRATEGIES
from .trend_complete import TREND_COMPLETE_STRATEGIES

# 合併所有趨勢策略（18 個）
ALL_TREND_STRATEGIES = {**HULL_TEMA, **ADVANCED_TREND_STRATEGIES, **TREND_COMPLETE_STRATEGIES}

__all__ = ['ALL_TREND_STRATEGIES', 'HULL_TEMA', 'ADVANCED_TREND_STRATEGIES', 'TREND_COMPLETE_STRATEGIES']
